parameters:
  repo: ''

jobs:
- job: buildRepoMacos
  displayName: 'Compile Package - MacOS'
  timeoutInMinutes: 150
  pool:
    vmImage: 'macOS-latest'
 
  steps:

  # Manually adding conda to the PATH is a step required by Microsoft
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'
  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
  # We need to take ownership if we want to update conda or install packages globally
  - bash: sudo chown -R $USER $CONDA
    displayName: 'Take ownership of conda installation'
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'Build'
      packageSpecs: 'python=3.7'
  - bash: |
      wget https://raw.githubusercontent.com/fermi-lat/ci/master/azure_templates/dependencies.txt
      conda install --yes --quiet -c conda-forge -c fermi --file=dependencies.txt
      rm dependencies.txt
    displayName: 'Setup Build environment'
  - bash: |
      repoman --remote-base https://github.com/fermi-lat checkout --force --develop ScienceTools conda
      rm -rf ${{ parameters.repo }}
      git clone https://github.com/fermi-lat/${{ parameters.repo }}
    displayName: 'Clone Repository'
  - bash: |
      scons -C ScienceTools --site-dir=../SConsShared/site_scons --conda=$(CONDA_PREFIX) --use-path --with-cc="$(CONDA_PREFIX)/bin/cc" --with-cxx="$(CONDA_PREFIX)/bin/c++" --ccflags="$(CFLAGS)" --cxxflags="-std=c++14 $(CXXFLAGS)" --ldflags="$(LDFLAGS) -Wl,-rpath,$(CONDA_PREFIX)/fermitools/lib:$(CONDA_PREFIX)/lib" --compile-opt ${{ parameters.repo }}
    displayName: 'Compile Package'    
