parameters:
  repo: ''

jobs:

- job: buildRepoLinux
  displayName: 'Compile Package - Linux'
  timeoutInMinutes: 150
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # This step is necessary because Conda no longer carries gcc-4.x 
  # compilers.  This can be removed once the Fermitools are C++11
  # compliant. 
  - bash: |
      sudo update-alternatives --remove-all gcc
      sudo update-alternatives --remove-all g++
      sudo apt-get install --yes gcc-4.8 g++-4.8
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
      sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
      sudo update-alternatives --set cc /usr/bin/gcc
      sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
      sudo update-alternatives --set c++ /usr/bin/g++
      which gcc
      gcc --version
    displayName: 'Install and set up gcc-4.8'
  # Manually adding conda to the PATH is a step required by Microsoft
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'Build'
      packageSpecs: 'python=2.7'
  - bash: |
      conda install --yes --quiet -c conda-forge/label/cf201901 -c fermi fermi-repoman scons swig
      conda install --yes --quiet --only-deps -c conda-forge/label/cf201901 -c fermi fermitools
    displayName: 'Setup Build environment'
  - bash: |
      repoman --remote-base https://github.com/fermi-lat checkout --force --develop ScienceTools conda
      rm -rf ${{ parameters.repo }}
      git clone https://github.com/fermi-lat/${{ parameters.repo }}
    displayName: 'Clone Repository'
  - bash: |
      mkdir -p $(CONDA_PREFIX)/include/fftw
      ln -s $(CONDA_PREFIX)/include/fftw3.* $(CONDA_PREFIX)/include/fftw
    displayName: 'FFTW relinking'
  - bash: scons -C ScienceTools --site-dir=../SConsShared/site_scons --conda=$(CONDA_PREFIX) --use-path --with-cc=/usr/bin/gcc --with-cxx=/usr/bin/g++ --ccflags="-O2" --cxxflags="-O2 -std=c++11" --ldflags="-Wl,-fopenmp,-rpath,$(CONDA_PREFIX)/lib,-rpath,$(CONDA_PREFIX)/lib/root,-rpath,$(CONDA_PREFIX)/lib" ${{ parameters.repo }}
    displayName: 'Compile Package'
