parameters:
  repo: ''

jobs:
- job: buildRepoMacos
  displayName: 'Compile Package - MacOS'
  timeoutInMinutes: 150
  pool:
    vmImage: 'macOS-latest'
 
  steps:

  # Manually adding conda to the PATH is a step required by Microsoft
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'
  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
  # We need to take ownership if we want to update conda or install packages globally
  - bash: sudo chown -R $USER $CONDA
    displayName: 'Take ownership of conda installation'
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'Build'
      packageSpecs: 'python=3.7'
  - bash: |
      git clone --recurse-submodules https://github.com/fermi-lat/ScienceTools.git
      rm -rf ScienceTools/src/${{ parameters.repo }}
      cd ScienceTools/src/
      git clone https://github.com/fermi-lat/${{ parameters.repo }}
    displayName: 'Clone Repository'
  - bash: |
      cd ScienceTools
      conda env create -n fermi-dev -f environments/fermitools-develop-osx.yml
      source activate fermi-dev
    displayName: 'Setup Build environment'
  - bash: |
      cmake -S . -B RelWithDebInfo -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX+PATH=$CONDA_PREFIX
      cmake --build RelWithDebInfo --parallel --target=${{ parameters.repo }}
    displayName: 'Compile Package'
