parameters:
  repo: ''

jobs:

- job: buildRepoLinux
  displayName: 'Compile Package - Linux'
  timeoutInMinutes: 150
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # Manually adding conda to the PATH is a step required by Microsoft
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'
  - bash: |
      wget https://raw.githubusercontent.com/fermi-lat/ci/master/azure_templates/dependencies.txt
      conda install --yes -c conda-forge -c fermi --file=dependencies.txt
      rm dependencies.txt
    displayName: 'Setup Build environment'
  - bash: |
      repoman --remote-base https://github.com/fermi-lat checkout --force --develop ScienceTools 
      rm -rf ${{ parameters.repo }}
      git clone https://github.com/fermi-lat/${{ parameters.repo }}
    displayName: 'Clone Repository'
  - bash: scons -C ScienceTools --site-dir=../SConsShared/site_scons --conda=$(CONDA_PREFIX) --use-path --with-cc="$(CONDA_PREFIX)/bin/cc" --with-cxx="$(CONDA_PREFIX)/bin/c++" --cxxflags="-std=c++14" --ldflags="-Wl,-rpath,$(CONDA_PREFIX)/fermitools/lib:$(CONDA_PREFIX)/lib" --compile-opt ${{ parameters.repo }}
    displayName: 'Compile Package'
